import { chromium, BrowserContext, Page } from "playwright";
import path from "path";
import fs from "fs";

let browserContext: BrowserContext | null = null;

export async function getBrowserContext(): Promise<BrowserContext> {
  if (browserContext) return browserContext;

  const userDataDir = path.resolve(process.cwd(), "chatgpt_local_profile");
  const headless = process.env.PLAYWRIGHT_HEADLESS !== "false" && process.env.PLAYWRIGHT_HEADLESS !== "0";

  try {
    browserContext = await chromium.launchPersistentContext(userDataDir, {
      headless: headless,
      args: ["--disable-blink-features=AutomationControlled"],
      viewport: { width: 1280, height: 720 },
    });
  } catch (error: any) {
    if (error.message.includes("Opening in existing browser session")) {
      const fallbackDir = path.resolve(process.cwd(), "chatgpt_local_profile_fallback");
      browserContext = await chromium.launchPersistentContext(fallbackDir, {
        headless: headless,
        args: ["--disable-blink-features=AutomationControlled"],
        viewport: { width: 1280, height: 720 },
      });
    } else {
      throw error;
    }
  }

  return browserContext;
}

export async function generateChatGPTImage(
  coverPath: string,
  prompt: string,
  title: string
): Promise<string> {
  const context = await getBrowserContext();
  const page = await context.newPage();

  try {
    await page.goto("https://chatgpt.com/");

    // Wait for the chat input
    const chatInputSelector = '#prompt-textarea, textarea, div[contenteditable="true"]';
    try {
      await page.waitForSelector(chatInputSelector, { timeout: 30000 });
    } catch (e) {
      throw new Error("Could not find ChatGPT input. Are you logged in? Set PLAYWRIGHT_HEADLESS=false in your .env, run the server, and log in to ChatGPT first.");
    }

    // Upload cover image
    const fileInput = await page.$('input[type="file"]');
    if (fileInput) {
      await fileInput.setInputFiles(coverPath);
    } else {
      throw new Error("Could not locate attachment button in ChatGPT. UI may have changed.");
    }

    await page.waitForTimeout(2000);

    // Enter prompt
    await page.fill(chatInputSelector, prompt);
    await page.waitForTimeout(1000);

    // Send
    const sendBtn = await page.$('button[data-testid="send-button"]');
    if (sendBtn) {
      await sendBtn.click();
    } else {
      await page.keyboard.press("Enter");
    }

    // Wait for generated image
    // ChatGPT might use alt="Generated by DALL·E" or alt="Generated image"
    const imgSelector = 'img[alt*="Generated image"], img[alt*="Generated by DALL·E"], img[src*="dalle"]';
    await page.waitForSelector(imgSelector, { timeout: 90000 });
    await page.waitForTimeout(3000); // Wait for blobs to settle

    // Extract image base64
    const b64Data = await page.evaluate(async (sel) => {
      const img = document.querySelector(sel) as HTMLImageElement;
      if (!img) return null;
      try {
        const res = await fetch(img.src);
        const blob = await res.blob();
        return new Promise<string>((resolve) => {
          const reader = new FileReader();
          reader.onloadend = () => resolve(reader.result as string);
          reader.readAsDataURL(blob);
        });
      } catch (e) {
        return null;
      }
    }, imgSelector);

    if (b64Data) {
      return b64Data; // Returns data:image/png;base64,...
    } else {
      throw new Error("Failed to extract raw image from OpenAI.");
    }
  } finally {
    await page.close();
  }
}

export async function generateChatGPTText(prompt: string): Promise<string> {
  const context = await getBrowserContext();
  const page = await context.newPage();

  try {
    await page.goto("https://chatgpt.com/");

    // Wait for chat input
    const chatInputSelector = '#prompt-textarea, textarea, div[contenteditable="true"]';
    try {
      await page.waitForSelector(chatInputSelector, { timeout: 30000 });
    } catch (e) {
      throw new Error("Could not find ChatGPT input. Are you logged in? Set PLAYWRIGHT_HEADLESS=false in your .env, run the server, and log in to ChatGPT first.");
    }

    // Try to safely set innerHTML if fill doesn't work well for large text
    await page.evaluate((args) => {
      const el = document.querySelector(args.sel) as HTMLElement;
      if (el) {
        el.innerHTML = `<p>${args.prompt.replace(/\\n/g, '<br>')}</p>`;
        el.dispatchEvent(new Event('input', { bubbles: true }));
      }
    }, { sel: chatInputSelector, prompt });

    await page.waitForTimeout(1000);
    await page.keyboard.press("Enter");

    // Wait for response to finish generating
    await page.waitForSelector('div[data-message-author-role="assistant"]', { timeout: 30000 });
    
    // Wait for the send button to re-appear or stop button to disappear
    try {
      await page.waitForSelector('button[data-testid="send-button"]:not([disabled])', { state: "visible", timeout: 60000 });
    } catch (e) {
      // Fallback timeout
      await page.waitForTimeout(5000);
    }

    // Extract text
    const responseElements = await page.$$('div[data-message-author-role="assistant"]');
    if (responseElements.length === 0) {
      throw new Error("Failed to locate ChatGPT response.");
    }

    const lastResponse = responseElements[responseElements.length - 1];
    const text = await lastResponse.innerText();
    return text;
  } finally {
    await page.close();
  }
}
